### ISSUE TITLE
UTF characters get messed up

### ISSUE THREAD

**Issue by ywen** [dblock/jenkins-ansicolor-plugin#18]
I am wondering do you know what happens if I have some special char in the output looks like this when in "raw" mode of console output

![screenshot](http://i.imgur.com/H4VZd.png)

After being parsed by the plugin, it becomes:

![screenshot](http://i.imgur.com/7A5gc.png)

Is it possible for the plugin to maintain the characters? Thanks

**Comment by hashar** [comment]
I took unicode code point for check marks from https://en.wikipedia.org/wiki/Check_mark#Unicode

You can then use zsh echo command (bash 4 printf would work as well):

    zsh -c 'for char in 237B 2610 2611 2705 2713 2714; do echo -e \\u$char; done;'

One would want to insert ANSI code to trigger processing by the plugin.  The above command does output the unicode just fine.

**Comment by dblock** [comment]
@hashar @ywen So do we have a bug with the AnsiColor plugin here or not?

**Comment by ywen** [comment]
It has been a while since I used this. So I don't know. I am going to close the issue.
