### ISSUE TITLE
Implement full xterm-256color range (probably needs JANSI changes)

### ISSUE THREAD

**Issue by ejelly** [dblock/jenkins-ansicolor-plugin#44]
This includes support for xterm's 256 color cube.

**Comment by PierreR** [comment]
That would make `92` to be display as green ?
```
printf "\e[92mHello World\e[0m\n"
```
That would be awesome because I am missing this color badly ;-)

**Comment by Joe-Merten** [comment]
Should be done now due to #96 / #98.

**Comment by dblock** [comment]
Closing.
