### ISSUE TITLE
Some escape sequences not recognized?

### ISSUE THREAD

**Issue by staeke** [dblock/jenkins-ansicolor-plugin#47]
It seems some escape sequences are not recognized. This is what are Jenkins looks like if ANSI Color is not turned on

![screen shot 2015-01-30 at 17 45 42](https://cloud.githubusercontent.com/assets/292397/5986296/e035ec4e-a8a7-11e4-8bf6-cd0a0f0048d8.png)

This is what it looks like with it turned on
![screen shot 2015-01-30 at 17 45 28](https://cloud.githubusercontent.com/assets/292397/5986300/f1dc6acc-a8a7-11e4-861f-a0387dc038e1.png)

As you can see, the first escape code (24) is recognized (no underline on next row), but the (39) escape code seems not to be. Any advice on how to fix or is this a bug?

**Comment by ejelly** [comment]
Can you attach the actual build logs? A few parts where escaping happens correctly and where it doesn't is enough, you can also redact any sensible information if there is any.

**Comment by staeke** [comment]
Sure. I e-mailed you one. Hope that's ok

**Comment by hashar** [comment]
Seems that is an issue with npm and or grunt

**Comment by Joe-Merten** [comment]
Imho fixed due to PR #28 and can be closed.
Both `esc[39m` and `esc[49m` are working as expected during my tests with ansicolor 0.4.3.

**Comment by dblock** [comment]
Closing.

**Comment by hashar** [comment]
Indeed works fine for me now with 0.4.3 . Thanks!
