### ISSUE TITLE
No color ouput with python environment

### ISSUE THREAD

**Issue by x00xer** [dblock/jenkins-ansicolor-plugin#49]
Hey, I have some strange problem with AnsiColor.

 I can see colorized output in jenkins when I'm running simple (empty) project with something like this
```bash
echo -e "\e[31mRed Text\e[0m" echo -e "\e[42mGreen Background\e[0m"
```

But it does not work (even ANSI control codes not visible) when I'm running functional tests ??

What should I check first ?

this is how I run them
```bash
#!/bin/bash -ex
source /var/lib/jenkins/virtualenvs/testing-standard/bin/activate
DOMAIN=$DOMAIN sauron --name=website features/website.feature $SCENARIOS
```

**Comment by dblock** [comment]
Does the README example work?

```
printf "\e[31mHello World\e[0m\n"
printf "Normal \e[1mBold\e[0m\n"
printf "Normal \e[4mUnderlined\e[0m\n"
```

**Comment by x00xer** [comment]
https://www.dropbox.com/s/qfwxcvlyh3ks1z1/Screenshot%202015-02-04%2017.15.10.png?dl=0

this is the result

**Comment by dblock** [comment]
There's a note in the README on Bash:

```
If you commonly use Zsh as your login shell, it's important to keep in mind that the echo command (shell builtin) supports character escaping.

Bash however, does not.

This can cause you a bit of confusion. For example, if you test your shell scripts (which use echo) in Zsh, and they work fine. Then you try to run them as part of a job on Jenkins (which will use be using Bash by default), it's quite possible you won't see colorized output, instead, you only see the ANSI control codes, still embedded in your text.

There are ways around this, however, we recommend you use the printf command instead. It'll just work everywhere, and allow \e, \033 or \x1b to be used as the escape character.

For example:

printf "\e[31mHello\e[0m\n"
printf "\033[31mHello\033[0m\n"
printf "\x1b[31mHello\x1b[0m\n"
Will all print Hello in red on any system / shell that has printf (ie. anything POSIX compliant)
```

Looks like that?

**Comment by x00xer** [comment]
Sorry, but Why ?

I use  
```bash
echo
```

and in empty project and it works, but when I use python to run functional tests color output does not work anymore :(
Is it means that python do not provide color ? or bash settings turning it off ? or coloransi does not work ?

Thanks.

**Comment by dblock** [comment]
It's bash, without `-e` I it renders the text as is, but what we want it to do is to convert `\e[31m` into an actual ESC control character followed by 31m. 

If you control the `echo`, try adding `-e` to it explicitly, does that do anything?

**Comment by ejelly** [comment]
I think what @x00xer is getting at is that it works fine with echo (thus confirming that the plugin is correctly installed), but his Python output isn't colorized. 

My impression is that it isn't outputting any escape sequences at all. There might be a parameter to enable it for non-terminal output.

**Comment by ejelly** [comment]
@x00xer, what is the test framework you're using called? I'm not familiar with that.

**Comment by x00xer** [comment]
the funny thing the output was ok before I've start to deal with python environments etc...
means I need to investigate in that direction.

**Comment by ejelly** [comment]
I think it's pretty safe to say that the problem doesn't lie with the ansicolor plugin at least, I don't think your test system is currently outputting any escape codes at all.

**Comment by dblock** [comment]
Lets close this. Comment with the details if you find the problem @x00xer please.
