### ISSUE TITLE
How to enable with Workflow projects?

### ISSUE THREAD

**Issue by chook** [dblock/jenkins-ansicolor-plugin#50]
I created a Workflow job, and there's no Build Environment to enable AnsiColor from.
I'm talking about the official [workflow aggregator](https://github.com/jenkinsci/workflow-plugin). 

Any thoughts?

**Comment by dblock** [comment]
Looks like a feature request.

**Comment by chook** [comment]
Thanks, I guess :) Is there a way to install AnsiColor as a global "Ansi all the consoles you see"? or is that another feature request? :)

**Comment by dblock** [comment]
That's open as https://github.com/dblock/jenkins-ansicolor-plugin/issues/2 already.

**Comment by qvicksilver** [comment]
I created a SimpleBuildWrapper that does what you are looking for: https://github.com/dblock/jenkins-ansicolor-plugin/pull/54

**Comment by qvicksilver** [comment]
@chook #54 has just been merged

**Comment by dblock** [comment]
Closing via #54.

**Comment by markhu** [comment]
I'm not convinced the workaround is good enough to close this issue. Wouldn't the full solution be either a check-box and/or Snippet generator?

**Comment by dblock** [comment]
Maybe open a clearer issue that describes the improvement on top of the workaround @markhu?
