### ISSUE TITLE
Please tag a new version (0.4.2?)

### ISSUE THREAD

**Issue by hashar** [dblock/jenkins-ansicolor-plugin#52]
Previous version 0.4.1 is from December 11 2014.  Would you mind tagging a new version?

**Comment by dblock** [comment]
cc: @ejelly

**Comment by dblock** [comment]
@ejelly you're alive? Want to cut a release? I'll do it if I don't hear from him ...

**Comment by dblock** [comment]
@qvicksilver I'd be happy to give you committer/release rights if you're willing to cut us a release and help with the library. Interested? Email me dblock[at]dblock[dot]org.

**Comment by dblock** [comment]
https://github.com/dblock/jenkins-ansicolor-plugin/issues/57 could be a blocker before release.

**Comment by ejelly** [comment]
Ah, only read this now, which also shows how responsive I currently am. I have to hold off on contributing for a while, because my free time remains limited for now (and in my previous job, I used the plugin as part of it, which gave me the luxury of working on the plugin during my actual day job).

**Comment by dblock** [comment]
@qvicksilver Want to cut a release now that we have https://github.com/dblock/jenkins-ansicolor-plugin/pull/62?

**Comment by qvicksilver** [comment]
@dblock sure! All I have to do is follow the instructions?

**Comment by dblock** [comment]
Right. I think somewhere I have to give you access to something :) you already have commiter access to github.

**Comment by qvicksilver** [comment]
As far as I can tell 0.4.2 has now been released.

**Comment by hashar** [comment]
GitHub has the tag:

    ansicolor-0.4.2 … 801390b

It appeared in the Jenkins update center.  Well done and thank you @qvicksilver and @dblock !

**Comment by hashar** [comment]
Sorry closed too fast.  You might want to update the wiki page https://wiki.jenkins-ci.org/display/JENKINS/AnsiColor+Plugin

Some plugins list the changelog on the wiki page which is very handy :-)

**Comment by qvicksilver** [comment]
Not sure how to make version updates stick on the wiki, the preview shows version 0.4.2 but nothing seems to happen after saving.

**Comment by hashar** [comment]
Seems good now. Probably a side effect due to caching.

**Comment by dblock** [comment]
Awesome, thanks @qvicksilver.
