### ISSUE TITLE
ability to detect and hyperlink file references

### ISSUE THREAD

**Issue by ssbarnea** [dblock/jenkins-ansicolor-plugin#76]
Imagine that your build process is generating some verbose logs which are saved as files. 
It would be really nice if this plugin would recognize file references like `dist/pip.log` and hyperlink them so you could just click on the file to load it.

**Comment by dblock** [comment]
I think that is outside of scope of this plugin, as we're only concerned with ANSI coloring. But this could be something useful and built the same way as jenkins-ansicolor.

I'll close this.
