### ISSUE TITLE
Improve pipeline enablement and making it optional

### ISSUE THREAD

**Issue by ssbarnea** [dblock/jenkins-ansicolor-plugin#80]
Now using Jenkins pipelines is becoming the norm instead of the weird-use-case and we do need an improved way to enable the AnsiColorBuildWrapper.

Have a look at the [Timestamper](https://wiki.jenkins-ci.org/display/JENKINS/Timestamper) plugin which now supports the nice DSL syntax:

```
timestamps {
    // code goes here
    }
```

To make the usage even better I would like to be able to have some kind of condition: if ansi plugin is present enable it, or continue if not. 

With these two small additions we could write much better Jenkins pipelines and we would avoid unpleasant surprises if it happens to have the plugin not installed. Build will continue, which is much better than having it broken because the ansicolor plugin was missing.

PS. Please mind that's possible for the plugin to be broken at some point and that's why is much better not to break continuity and continue to work without the feature. Optionally we could throw a warning message, but what matters is to avoid breakages.

**Comment by dblock** [comment]
This sounds reasonable, please feel free to contribute.

**Comment by JeanMertz** [comment]
Quick question:

Why should I as a `Jenkinsfile` maintainer be concerned about enabling/disabling color output?

Shouldn't this plugin simply be activated on the server-side, and "just work" for any pipelines running, with or without color output?

**Comment by dblock** [comment]
@JeanMertz I think this is purely historical. IMO this should be the default and available with the default Jenkins distribution.

**Comment by Bagira80** [comment]
A nice side-effect of this feature-request would be:

A DSL, similar to the one of [Timestamper](https://wiki.jenkins-ci.org/display/JENKINS/Timestamper), would also enable using the ANSIcolor plugin outside of `node`-blocks. (See [this](https://issues.jenkins-ci.org/browse/JENKINS-30142) Timestamper issue for some explaining comments.)

**Comment by markhu** [comment]
To put a finer point on @JeanMertz comment: Is there a way to simply enable AnsiColor with a checkbox in the UI instead of code in Jenkinsfile?

**Comment by dblock** [comment]
I believe https://github.com/dblock/jenkins-ansicolor-plugin/pull/83 closes this, can someone please try?

**Comment by cpoenisch** [comment]
My PR allows to use a simpler Pipeline syntax without the need for the build wrapper. But makes the usage not optional depending on whether the plugin is installed or not. In negative case you will always get `java.lang.NoSuchMethodError: No such DSL method 'ansiColor' found among steps...`
So either put your formatted content inside the `ansiColor` step or just log as plain text.

**Comment by Bagira80** [comment]
I can confirm, that the new syntax works, even without a surrounding node.

**Comment by dblock** [comment]
Should this be closed?

**Comment by subos2008** [comment]
@dblock yes, I think reading through it that the OP's request is satisfied. There is also the request from @markhu that we have a way to enable this globally (which I am 100% in favour of) but that was already requested separately in [https://github.com/dblock/jenkins-ansicolor-plugin/issues/2]
