### ISSUE TITLE
[question] Does this work out of the box with chalk?

### ISSUE THREAD

**Issue by ericfrancis** [dblock/jenkins-ansicolor-plugin#81]
Does this work out of the box with [chalk](https://github.com/chalk/chalk)?

I'm using `chalk.green` and `chalk.red`, and the `xterm` option. Not seeing color in my jenkins terminal.

**Comment by dblock** [comment]
I would start with something simpler from https://github.com/dblock/jenkins-ansicolor-plugin#does-it-even-work and then throw chalk in there and we'll know!

**Comment by ericfrancis** [comment]
@dblock Great idea! I will do the check. Thanks.

**Comment by willpracht** [comment]
I believe this does. We use Chalk for a few things.

**Comment by dblock** [comment]
I'm going to call it a done and close.

**Comment by ericfrancis** [comment]
@willpracht did you have to do anything special?

**Comment by willpracht** [comment]
@ericfrancis - Nope. I am running Chalk within some Gulp tasks and such. It adds the ANSI codes, ANSI Color plugin seems to parse them correctly, colorizing the output.

**Comment by ericfrancis** [comment]
@willpracht lame. I'm using chalk.red and .green. Not seeing the colors. I'll mess around with it some more.

**Comment by willpracht** [comment]
@ericfrancis Are you at least seeing the ANSI codes in your console? If so, then it's a ANSI Color Plugin problem. If not, then start there. Run your script locally. See if you can reproduce that way.

**Comment by ericfrancis** [comment]
The test script on the plugin readme did show color.

**Comment by willpracht** [comment]
@ericfrancis Ah. So it looks like might be your script then. If you run your script locally, do you see colors?

**Comment by ericfrancis** [comment]
@willpracht Yep. Do you run your script with `set -x` ?

**Comment by willpracht** [comment]
@ericfrancis Nope, I use `+x`.

**Comment by vstaykov** [comment]
Any progress here? I struggle with the same issue?

**Comment by sabberworm** [comment]
@vstaykov you might try starting your script with

```bash
export FORCE_COLOR=1
```

**Comment by tandibar** [comment]
For anyone coming around here an searching for the solution, this is what worked for me:
```groovy
node {
    ansiColor('xterm') {
        withEnv(['FORCE_COLOR=3']) {
            ...
            sh "some-node-script-using-chalk.js"
            ...
        }
    }
}
```
