### ISSUE TITLE
Italic attribute and some others not recognized

### ISSUE THREAD

**Issue by Joe-Merten** [dblock/jenkins-ansicolor-plugin#89]
I had created a test matrix which is located within the comments of [this python script](https://github.com/Joe-Merten/Jfe/blob/master/Framework/tools/AnsiColors.py).

Most important lacks for my opinion:

- `esc[3m` / `esc[23m`  italic on / off
- `esc[7m` / `esc[27m`  inverse on / off
  - see also: https://github.com/dblock/jenkins-ansicolor-plugin/issues/64
- `esc[9m` / `esc[29m`  strikeout on / off
- `esc[90m` … `esc[97m` and `esc[100m` … `esc[107m`  bright colors
  - see also: https://github.com/dblock/jenkins-ansicolor-plugin/issues/16
- `esc[38;…m` / `esc[48;…m`  256 colors and 24 bit colors
  - see also: https://github.com/dblock/jenkins-ansicolor-plugin/issues/44
  - and: https://issues.jenkins-ci.org/browse/JENKINS-24378
- `esc[28m`  reveal / conceal off

How to reproduce: Just put the above mentioned [python script](https://github.com/Joe-Merten/Jfe/blob/master/Framework/tools/AnsiColors.py) into a Jenkins freestyle or pipeline job with AnsiColor plugin enabled and then check the console output of this job in the web browser.

**Comment by dblock** [comment]
The next step is to turn this into a test in this project, PRs welcome.

**Comment by Joe-Merten** [comment]
I might contribute some test and / or code. What's a good point to start?
I have some knowledge in Java, C++ and some other languages, but have not doing plugin development before.

**Comment by Joe-Merten** [comment]
Hmm, saw https://github.com/dblock/jenkins-ansicolor-plugin/pull/72 which is listed under 0.4.3 in the changelog. But for me, `esc[91m` etc. still won't work.

**Comment by Joe-Merten** [comment]
With PR #90, this is done for:

- `esc[3m` / `esc[23m`  italic on / off
- `esc[9m` / `esc[29m`  strikeout on / off
- `esc[28m`  reveal / conceal off

and additional:

- `esc[51m` / `esc[54m`  framed on / off
- `esc[53m` / `esc[55m`  overlined on / off

Still todo:

- `esc[7m` / `esc[27m`  inverse on / off
  - see also: https://github.com/dblock/jenkins-ansicolor-plugin/issues/64
- `esc[90m` … `esc[97m` and `esc[100m` … `esc[107m`  bright colors
  - see also: https://github.com/dblock/jenkins-ansicolor-plugin/issues/16
- `esc[38;…m` / `esc[48;…m`  256 colors and 24 bit colors
  - see also: https://github.com/dblock/jenkins-ansicolor-plugin/issues/44
  - and: https://issues.jenkins-ci.org/browse/JENKINS-24378

I'll now analyze, why #72 for `esc[90m` won't work.

And for `esc[7m`, seems we always have to track the current fg/bg color, isn't it? Could not find a html feature for »inverse text«. Other ideas?

**Comment by Joe-Merten** [comment]
With PR #92, this is now also done for:

- `esc[90m` … `esc[97m` and `esc[100m` … `esc[107m`  bright / high intensity colors

Still todo:

- `esc[7m` / `esc[27m`  inverse on / off
  - see also: https://github.com/dblock/jenkins-ansicolor-plugin/issues/64
- `esc[38;…m` / `esc[48;…m`  256 colors and 24 bit colors
  - see also: https://github.com/dblock/jenkins-ansicolor-plugin/issues/44
  - and: https://issues.jenkins-ci.org/browse/JENKINS-24378

Still have no idea what's the best way how to implement `esc[7m` in html. What does you suggest?
See also http://stackoverflow.com/questions/42585913/how-to-display-inverse-text-in-html

For the next' I'll have a look to `esc[38;…m` / `esc[48;…m` for 256 colors and 24 bit colors support. Unfortunately, cannot jansi `private boolean processEscapeCommand()`, so have to implement a small state machine to collect the additional arguments for 38 & 48.

**Comment by dblock** [comment]
I think SO is right on.

**Comment by Joe-Merten** [comment]
For `esc[38;…m` / `esc[48;…m` it needs support from jansi. See also [jansi PR #72](https://github.com/fusesource/jansi/pull/72). Now waiting until they accept my PR. Hmm, did I also have to wait until they make a new release before I can use this here?

**Comment by dblock** [comment]
Basically yes, to fix an issue that is inside Jansi you have to wait till their release to package a newer version.

**Comment by Joe-Merten** [comment]
Hmm, seeing the jansi guys had their last release 1.14 on 2016-10-04. I think I'll wait some days and see what happens. I maybe decide for that »private dependency thing« if it takes too long. No I'll check what to do for `esc[7m`.

**Comment by Joe-Merten** [comment]
Regarding `esc[7m`, I think there is no other way than tracking each change of foreground and background color. But if the `esc[7m` arrives before any color changes (or just after a `esc[m`), I have to know about the default foreground and background colors.
For the dark themes (Vga and GnomeTerminal), I saw that there are defaults defined in `AnsiColorMap.java`, but for the other both not. So I see two possible options for the both light themes (xterm and css):

- using hard coded defaults (e.g. black text on white background)
- or using foreground = index 0 and background = index 7 (for background, maybe `colorMap.getBright()` instead of `colorMap.getNormal()`)

What's your opinion about this?

**Comment by dblock** [comment]
I'd keep it simple with 1.

**Comment by Joe-Merten** [comment]
Reading about customized color maps:
![ansicolor-config](https://cloud.githubusercontent.com/assets/6552470/23623625/fc4bf6ba-02a2-11e7-8f16-e30684b5105b.png)
but cannot find this in the Jenkins web UI.
Want this for a bit more testing how my changes will work.

**Comment by Joe-Merten** [comment]
@dblock: Could you lead me to that »customized color maps« UI?

**Comment by dblock** [comment]
Manage Jenkins, ANSI Color, Advanced

**Comment by Joe-Merten** [comment]
Manage Jenkins → Configure System → ANSI Color → Advanced

**Comment by Joe-Merten** [comment]
Don't know exactly how to »… drop in a private dependency here to expedite something.« Now just created #96 which build and works on my machine when also locally applying [jansi PR #72](https://github.com/fusesource/jansi/pull/72).

**Comment by dblock** [comment]
This is closed via https://github.com/dblock/jenkins-ansicolor-plugin/pull/98, right? Closing.
