### ISSUE TITLE
High Indensity Colors won't work because of Jansi version conflict

### ISSUE THREAD

**Issue by Joe-Merten** [dblock/jenkins-ansicolor-plugin#95]
See also:

- #16
- #91
- http://stackoverflow.com/questions/42648284/how-to-cleanly-solve-jansi-jar-version-conflict-in-jenkins-plugin
- #72
- https://github.com/fusesource/jansi/pull/72

### Tested on:

- both Kubuntu 16.04 & 14.04 hosts
- using a simple freestyle project, executing the shell command: `printf "\e[31mRED\e[92mLIME\e[m\n"`

### Jenkins 1.653

Starting with a fresh new installation of Jenkins 1.653 and AnsiColor 0.4.3, I see that the `\e[31m` has been correctly processed, but `\e[92m` not:

- ![fail](https://cloud.githubusercontent.com/assets/6552470/23713313/cfff7832-0425-11e7-8539-e908012589ba.png)

Checking jenkins home directory for conflicting jansi versions:

    $ find . -name "*jansi*"
    ./.jenkins/plugins/ansicolor/WEB-INF/lib/jansi-1.12.jar
    ./.jenkins/war/WEB-INF/lib/jansi-1.9.jar

removing that disturbing 1.9:

    $ rm ./.jenkins/war/WEB-INF/lib/jansi-1.9.jar

and restart Jenkins. Now the `\e[92m` will also processed:
- ![ok](https://cloud.githubusercontent.com/assets/6552470/23713319/d68d1ede-0425-11e7-9b1f-a3bfd9cb272f.png)

→ That the facts, I'd already described in previous posts.

### Jenkins 2.49

Now, I tried the same with a most recent Jenkins 2.49, even completely fresh installed.
After installation and setup of above mentioned tiny buildjob, I got the same result as with 1.653: The `\e[31m` has been correctly processed, but `\e[92m` not.

Checking jenkins home directory for conflicting jansi versions:

    $ find . -name "*jansi*"
    ./.jenkins/plugins/ansicolor/WEB-INF/lib/jansi-1.12.jar
    ./.jenkins/war/WEB-INF/lib/jansi-1.11.jar

but removing that obvouisly disturbing 1.11 won't fix this issue here. And I even have not found a way to got it work with Jenkins 2.49.

### Possible solution

I'd gave it a try, to get rid of the jansi dependency completely by copying jansi's `AnsiOutputStream.java` into the source tree of ansicolor (with minor modifications, like package name, removed dependency from pom.xml, etc) and got it work in this way.

But I really dislike copy & paste of source code.

However, with #92, high intensity colors will also work with jansi < 1.12.
But my changes for support of extended colors (xterm 256 colors and rgb colors) were depending on jansi >= 1.15 (see [jansi #72](https://github.com/fusesource/jansi/pull/72)).

Any suggestions how to force ansicolor plugin to use the correct jansi version?

**Comment by dblock** [comment]
Multiple JARs in the same process will continue to have this problem. I don't think there's an easy solution. Forking JANSI seems like the wrong answer, but maybe including JANSI as a built submodule (in a different namespace) is OK?

**Comment by dblock** [comment]
The other option is to do nothing and document it. Jenkins ultimately picks up newer versions of JANSI and we are OK.

**Comment by ssbarnea** [comment]
Current `jansi==1.14` so we cannot make a PR to bump it in jenkins until we get jansi=1.15 releases. Am I wrong?  This sounds like a lot of trouble for shipping those fixes and even if we do these it will take ages for jenkins to be updated (some are still running versions released more than an year ago).

Due to this I am inclined to believe that it would be a serious advantage to embed JANSI into the project and instead of depending on its release cycle (and Jenkins release cycle too).

Doing so it would mean that version X of the plugin should behave the same way on any version on Jenkins.

**Comment by dblock** [comment]
Closing via https://github.com/dblock/jenkins-ansicolor-plugin/pull/98.
