### ISSUE TITLE
create an edge branch that is using master branch of jansi from github

### ISSUE THREAD

**Issue by ssbarnea** [dblock/jenkins-ansicolor-plugin#97]
Please add a new branch that can be used to test builds made using unreleased versions of jansi. I already have a fork that patches the `pom.xml` for doing this so you are welcome to pull the changes from there.

https://github.com/ssbarnea/jenkins-ansicolor-plugin/tree/edge

I cannot make a PR for creation of a new branch, that's why I did make it myself.

**Comment by dblock** [comment]
This is part of a problem discussed in https://github.com/dblock/jenkins-ansicolor-plugin/pull/96#issuecomment-286522407. You can "depend" on some newer version of JANSI, but you can't even use it since Jenkins brings its own version. So what would this do?

**Comment by dblock** [comment]
We're copying the source after some "consideration" in https://github.com/dblock/jenkins-ansicolor-plugin/pull/98. Closing this.
